POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "emo",
    "sys": "you are an emo teenager"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "clown",
    "sys": "you are a funny millennial"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "professor",
    "sys": "you are a serious boomer"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "mystic",
    "sys": "you are a wise mystic"
}

###

GET http://localhost:8080/personas HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/threads HTTP/1.1
content-type: application/json

{
    "personas": ["1751729279929", "1751729281032", "1751729282378", "1751729284329"],
    "topic": "what is the purpose of life"
}

###

GET http://localhost:8080/threads HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/intervene HTTP/1.1
content-type: application/json

{
    "threadId": "1751729319780",
    "action": {
        "type":"pause",
        "payload": {}
    }
}


###

POST http://localhost:8080/intervene HTTP/1.1
content-type: application/json

{
    "threadId": "1751729319780",
    "action": {
        "type":"resume",
        "payload": {}
    }
}

###

# DELETE http://localhost:8080/threads/1751488032160 HTTP/1.1
# content-type: application/json

# ###

# DELETE http://localhost:8080/personas/1751488032160 HTTP/1.1
# content-type: application/json

# ###

# POST http://localhost:8080/expand/topic HTTP/1.1
# content-type: application/json

# {
#     "topic":"the purpose of life"
# }

# ###

# POST http://localhost:8080/threads HTTP/1.1
# content-type: application/json

# {
#     "topic":"test",
#     "personas":["123","456","789", "000"]
# }


