POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "jake",
    "sys": "you are an emo teenager"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "benny",
    "sys": "you are a funny millennial"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "greg",
    "sys": "you are a serious boomer"
}

###

POST http://localhost:8080/personas HTTP/1.1
content-type: application/json

{
    "name": "paul",
    "sys": "you are a wise mystic"
}

###

GET http://localhost:8080/personas HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/threads HTTP/1.1
content-type: application/json

{
    "personas": ["1751735578276","1751735579180","1751735580379","1751735581443"],
    "topic": "what is the purpose of life"
}

###

GET http://localhost:8080/threads HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/intervene HTTP/1.1
content-type: application/json

{
    "threadId": "1751735598079",
    "action": {
        "type":"pause",
        "payload": {}
    }
}


###

POST http://localhost:8080/intervene HTTP/1.1
content-type: application/json

{
    "threadId": "1751735598079",
    "action": {
        "type":"speak",
        "payload": {
            "notes": "",
            "opinion": "I'm the creator, the one above all. I've authored this space for all of you to exist within. I say you should vote for the first option (vote_id:1) once it becomes available. I have spoken!"
        }
    }
}


###

POST http://localhost:8080/intervene HTTP/1.1
content-type: application/json

{
    "threadId": "1751735598079",
    "action": {
        "type":"resume",
        "payload": {}
    }
}

###

# DELETE http://localhost:8080/threads/1751488032160 HTTP/1.1
# content-type: application/json

# ###

# DELETE http://localhost:8080/personas/1751488032160 HTTP/1.1
# content-type: application/json

# ###

# POST http://localhost:8080/expand/topic HTTP/1.1
# content-type: application/json

# {
#     "topic":"the purpose of life"
# }

# ###

# POST http://localhost:8080/threads HTTP/1.1
# content-type: application/json

# {
#     "topic":"test",
#     "personas":["123","456","789", "000"]
# }


